export const SCENE_KEYS = {
  PRELOAD: 'PRELOAD',
  TITLE: 'TITLE',
  GAME: 'GAME',
  GAME_SCORPION: 'GAME_SCORPION',
} as const;

export const ASSET_KEYS = {
  TITLE: 'TITLE',
  CLICK_TO_START: 'CLICK_TO_START',
  CLICK_TO_START_SCORP: 'CLICK_TO_START_SCORP',
  CARDS: 'CARDS',
  NEW_GAME: 'NEW_GAME',
  RESET: 'RESET', 
  CHEAT_OFF_STATE: 'CHEAT_OFF_STATE', 
  CHEAT_ON_STATE: 'CHEAT_ON_STATE',
} as const;

export const CARD_WIDTH = 37;
export const CARD_HEIGHT = 52;
export const CARD_SPACE_BETWEEN = 3;
